//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public UserDetail()
        {
            this.UserPhotoes = new HashSet<UserPhoto>();
            this.UserUsers = new HashSet<UserUser>();
            this.UserUsers1 = new HashSet<UserUser>();
        }
    
        public long Id { get; set; }
        public string Email { get; set; }
        public string About { get; set; }
        public string Fullname { get; set; }
        public System.DateTime DateOfBirth { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<UserPhoto> UserPhotoes { get; set; }
        public virtual ICollection<UserUser> UserUsers { get; set; }
        public virtual ICollection<UserUser> UserUsers1 { get; set; }
    }
}
