//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPhoto
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public long PhotoId { get; set; }
    
        public virtual Photo Photo { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
